services:
  - type: web
    name: cv-analyzer
    env: node
    plan: free
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: npm run start
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: GITHUB_ID
        sync: false
      - key: GITHUB_SECRET
        sync: false
      - key: RATE_LIMIT_SALT
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cv-analyzer-db
          property: connectionString

databases:
  - name: cv-analyzer-db
    plan: free
